name: Run with Jaeger (host network)

on:
  workflow_dispatch:

jobs:
  run-jaeger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Jaeger (host network)
        run: |
          docker run -d --name jaeger \
            --network host \
            -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 \
            jaegertracing/all-in-one:latest

          echo "Jaeger started on host network — UI at http://localhost:16686"

      - name: Wait for Jaeger to be ready
        run: |
          echo "Waiting for Jaeger to start..."
          sleep 10

      - name: Run tests (example)
        run: |
          echo "Running tests while Jaeger is active..."
          # npr. mvn test ili pytest

      - name: Stop and remove Jaeger
        if: always()
        run: |
          echo "Stopping Jaeger..."
          docker stop jaeger || true
          docker rm jaeger || true
